services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/albestae/data/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - /home/albestae/data/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress_user}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_URL: ${WORDPRESS_URL:-https://albestae.42.fr}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE:-Inception}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER:-manager}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL:-manager@inception.com}
    secrets:
      - mysql_password
      - wordpress_admin_password
      - redis_password
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "127.0.0.1:${MARIADB_PORT:-3306}:3306"
    volumes:
      - /home/albestae/data/mysql:/var/lib/mysql
      - ./requirements/mariadb/tools/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress_user}
    secrets:
      - mysql_root_password
      - mysql_password
    networks:
      - inception
    restart: always

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - /home/albestae/data/redis:/var/lib/redis
      - ./requirements/bonus/redis/conf/redis.conf:/etc/redis/redis.conf:ro
    secrets:
      - redis_password
    networks:
      - inception
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - /home/albestae/data/wordpress:/var/www/html
      - ./requirements/bonus/ftp/conf/proftpd.conf:/etc/proftpd/proftpd.conf:ro
    secrets:
      - ftp_password
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

  static-website:
    build: ./requirements/bonus/static-website
    container_name: static-website
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - inception
    restart: always

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - /home/albestae/data/minecraft:/data
    environment:
      - EULA=TRUE
      - VERSION=1.20.4
      - TYPE=VANILLA
      - MEMORY=2G
      - ONLINE_MODE=FALSE
      - DIFFICULTY=normal
      - GAMEMODE=survival
      - MAX_PLAYERS=20
      - PVP=true
      - ALLOW_NETHER=true
      - ENABLE_COMMAND_BLOCK=false
      - MOTD=Inception Minecraft Server
    networks:
      - inception
    restart: always
    mem_limit: 2g
    memswap_limit: 2g

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_password:
    file: ./secrets/mysql_password
  wordpress_admin_password:
    file: ./secrets/wordpress_admin_password
  redis_password:
    file: ./secrets/redis_password
  ftp_password:
    file: ./secrets/ftp_password

networks:
  inception:
    driver: bridge